<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Votez pour le plus beau chien de la cte d, , Opale )_jouer - Copy</name>
   <tag></tag>
   <elementGuidId>4456e8e5-9f69-41b6-b8a8-0663f39c3e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;jouer&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jouer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f52941d-cc65-48d7-adf3-a4c9ad980f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jouer</value>
      <webElementGuid>05a81205-b8db-4ffe-a83a-d8801028f607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jouer</value>
      <webElementGuid>485fd80a-c25a-421e-865f-118fb720777c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9e74a90b-ece6-4227-a631-9fd378215da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bouton</value>
      <webElementGuid>8bff43e2-e507-4e16-b7c0-9a0321cbe543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Voter</value>
      <webElementGuid>aa5c8d7c-dc06-4f27-aae0-d5f4bade815e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jouer&quot;)</value>
      <webElementGuid>00162bfc-282b-459e-98cf-018b3d78299d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Concours photo  votez pour la plus bel_494087/iframe_nous organisons un concours photo ju_500439</value>
      <webElementGuid>a8f6d57e-6c2c-4f0b-b40a-5b80c5a3f484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//*[@id=&quot;jouer&quot;]</value>
      <webElementGuid>a8128de7-4bd5-46a6-8fe7-22a08fbe1af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
