<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(Votez pour le plus beau chien de la cte d, , Opale )_jouer</name>
   <tag></tag>
   <elementGuidId>b9af55fa-dd33-490a-a421-73862185f525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jouer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jouer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abe94340-73e7-41e9-860f-2bca9b438585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jouer</value>
      <webElementGuid>e56125ba-7a80-4a24-9da5-3e02f771c604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jouer</value>
      <webElementGuid>f258a5d1-c79b-4b65-914d-89d1d66a5724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2003d2e2-2395-4a5e-8d96-aea3afe6f1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bouton</value>
      <webElementGuid>b54984d2-3374-4f8d-83a3-62c0818446ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Voter</value>
      <webElementGuid>78eedb2a-c96e-4768-8cf8-e7b5dd3f5c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jouer&quot;)</value>
      <webElementGuid>d8576d43-836e-4df6-9054-5a807a2ea208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Concours photo  votez pour la plus bel_494087/iframe_nous organisons un concours photo ju_500439</value>
      <webElementGuid>a0020cb3-20bf-4f5a-b6d5-f79eff50a341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[@id='jouer']</value>
      <webElementGuid>a3597e20-0595-4aa0-9c28-0c90f515b83f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
