<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plus de votes</name>
   <tag></tag>
   <elementGuidId>cfacc7e1-182f-4717-9beb-c316216bce0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-heart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sortby&quot;]/div/div/select/option[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ab5582bb-9698-41a7-86a6-1d2a68d549b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-heart</value>
      <webElementGuid>8a70dc7f-0ada-4495-b42f-4816d17313f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gallery_image&quot;)/div[@class=&quot;gallery-zoom-container&quot;]/div[@class=&quot;gallery-container&quot;]/div[@class=&quot;gallery-diapo diapo-simple diapo1&quot;]/div[@class=&quot;thumbnail-info&quot;]/div[@class=&quot;thumbnail-wrapper&quot;]/div[@class=&quot;vote-type&quot;]/div[@id=&quot;vote-box&quot;]/a[@class=&quot;simple-vote&quot;]/i[@class=&quot;fa fa-heart&quot;]</value>
      <webElementGuid>c5ae9ae4-fdae-4b59-aeca-430347271281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Concours photo  votez pour la plus bel_494087/iframe_nous organisons un concours photo ju_500439</value>
      <webElementGuid>ca69c9bf-42a0-467c-b25d-b02d878c5273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//*[@id=&quot;sortby&quot;]/div/div/select/option[3]</value>
      <webElementGuid>10911295-9541-482c-abfa-6923abd48f9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
